backend:
  name: github
  repo: adamfysh/LastLarch-site
  branch: main

media_folder: images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }