backend:
  name: github
  repo: adamfysh/LastLarch-site
  branch: main
  auth_scope: repo
  client_id: YOUR_CLIENT_ID

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
